# Generated by Django 5.2.7 on 2025-10-28 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Rex, Luna, etc.', max_length=100, verbose_name='Nome do Pet')),
                ('slug', models.SlugField(blank=True, help_text='Deixe em branco para ser gerado automaticamente a partir do nome.', max_length=120, unique=True, verbose_name='URL Amigável (Slug)')),
                ('especie', models.CharField(choices=[('GATO', 'Gato'), ('CACHORRO', 'Cachorro'), ('COELHO', 'Coelho'), ('HAMSTER', 'Hamster'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10, verbose_name='Espécie')),
                ('raca', models.CharField(blank=True, help_text='Opcional. Ex: Vira-lata, Poodle, Siamês.', max_length=50, null=True, verbose_name='Raça')),
                ('idade', models.PositiveIntegerField(help_text='Idade aproximada em anos.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)], verbose_name='Idade (anos)')),
                ('descricao', models.TextField(help_text='Descreva a personalidade, história e necessidades do pet.', verbose_name='Descrição')),
                ('foto', models.ImageField(help_text='Envie uma foto nos formatos .jpg, .jpeg ou .png', upload_to='pets/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Foto')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EM_PROCESSO', 'Em Processo de Adoção'), ('ADOTADO', 'Adotado')], default='DISPONIVEL', max_length=20, verbose_name='Status da Adoção')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Pet para Adoção',
                'verbose_name_plural': 'Pets para Adoção',
                'ordering': ['-data_cadastro'],
                'constraints': [models.UniqueConstraint(fields=('nome', 'especie'), name='unique_pet_nome_especie')],
            },
        ),
    ]
