# Generated by Django 5.2.7 on 2025-10-29 02:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='foto',
        ),
        migrations.AddField(
            model_name='pet',
            name='foto_principal',
            field=models.ImageField(blank=True, help_text='Envie a foto destaque do pet em JPG, JPEG, PNG ou WEBP.', null=True, upload_to='pets/%Y/%m/%d/principal/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto principal'),
        ),
        migrations.AddField(
            model_name='pet',
            name='video',
            field=models.FileField(blank=True, help_text='Envie um vídeo curto do pet (.mp4, .mov, .avi, .mkv ou .webm).', null=True, upload_to='pets/%Y/%m/%d/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi', 'mkv', 'webm'])], verbose_name='Vídeo'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='especie',
            field=models.CharField(choices=[('CACHORRO', 'Cachorro'), ('GATO', 'Gato'), ('COELHO', 'Coelho'), ('PEIXE', 'Peixe'), ('PASSARO', 'Pássaro'), ('ROEDOR', 'Roedor'), ('REPTIL', 'Réptil'), ('OUTRO', 'Outro')], default='OUTRO', max_length=12, verbose_name='Espécie'),
        ),
        migrations.CreateModel(
            name='PetExtraPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='pets/%Y/%m/%d/galeria/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto adicional')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_extras', to='adocoes.pet', verbose_name='Pet')),
            ],
            options={
                'verbose_name': 'Foto adicional do pet',
                'verbose_name_plural': 'Fotos adicionais do pet',
                'ordering': ['ordem', 'data_envio', 'id'],
            },
        ),
    ]
