# Generated by Django 5.2.7 on 2025-10-31 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adocoes', '0002_remove_pet_foto_pet_foto_principal_pet_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pets_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente de Aprovação'), ('DISPONIVEL', 'Disponível'), ('EM_PROCESSO', 'Em Processo de Adoção'), ('ADOTADO', 'Adotado')], default='PENDENTE', max_length=20, verbose_name='Status da Adoção'),
        ),
    ]
